import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import MobileNavigation from "@/app/components/MobileNavigation";
import Navigation from "@/app/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
        <head>
            <script src="https://kit.fontawesome.com/3745fcc90b.js" crossOrigin="anonymous"></script>
        </head>

      <body className={inter.className}>

      <Navigation/>
      <MobileNavigation/>
      {children}
      </body>
    </html>
  );
}
